-- Custom SQL migration file, put you code below! --
INSERT INTO
	FLOW_USER_PROGRESS (USER_HASH, FLOW_ID, UPDATED_AT)
SELECT
	E.USER_HASH,
	E.FLOW_ID,
	E.EVENT_TIME
FROM
	EVENT E
WHERE
	NOT EXISTS (
		SELECT
			FUP.USER_HASH
		FROM
			FLOW_USER_PROGRESS FUP
		WHERE
			E.USER_HASH = FUP.USER_HASH
	)
	AND E.EVENT_TYPE IN ('finishFlow', 'cancelFlow')
	AND E.USER_HASH IS NOT NULL