-- Custom SQL migration file, put you code below! --
WITH
	CTE AS (
		SELECT
			E.USER_HASH,
			E.FLOW_ID,
			E.EVENT_TIME,
			ROW_NUMBER() OVER (
				PARTITION BY
					E.USER_HASH,
					E.FLOW_ID
				ORDER BY
					E.EVENT_TIME DESC
			) AS RN
		FROM
			EVENT E
		WHERE
			NOT EXISTS (
				SELECT
					FUP.USER_HASH
				FROM
					FLOW_USER_PROGRESS FUP
				WHERE
					E.USER_HASH = FUP.USER_HASH
					AND E.FLOW_ID = FUP.FLOW_ID
			)
			AND E.EVENT_TYPE IN ('finishFlow', 'cancelFlow')
			AND E.USER_HASH IS NOT NULL
	)

	
INSERT INTO
	FLOW_USER_PROGRESS (USER_HASH, FLOW_ID, UPDATED_AT)
SELECT
	USER_HASH,
	FLOW_ID,
	EVENT_TIME
FROM
	CTE
WHERE
	RN = 1