export const links = {
  twitter: "https://x.com/flows_sh",
  rbnd: "https://rbnd.studio",
  rbndGithub: "https://github.com/RBND-studio",
  status: "https://status.flows.sh",
  slack: "https://flows.sh/join-slack",
  signUp: "https://app.flows.sh/signup",
  logIn: "https://app.flows.sh/login",
  nextJsDemo: "https://nextjs.flows.sh",
  privacy: "https://flows.sh/privacy",
  terms: "https://flows.sh/terms",
  pricing: "https://flows.sh/pricing",
  changelog: "https://flows.sh/changelog",
  // docs
  docs: "https://flows.sh/docs",
  docsStepsEditor: "https://flows.sh/docs/creating-flows/steps-editor",
  docsInstallFlows: "https://flows.sh/docs/getting-started/install-flows",
  docsVerifyInstallation: "https://flows.sh/docs/getting-started/install-flows#verify-installation",
  docsContact: "https://flows.sh/docs/contact-us",
  docsStartFlow: "https://flows.sh/docs/creating-flows/start-flow",
  docsTargetFlow: "https://flows.sh/docs/creating-flows/targeting",
  docsFlowFrequency: "https://flows.sh/docs/creating-flows/frequency",
  docsStep: {
    tooltip: "https://flows.sh/docs/step-types/tooltip",
    modal: "https://flows.sh/docs/step-types/modal",
    wait: "https://flows.sh/docs/step-types/wait",
  },
  docsBranchTargeting: "https://flows.sh/docs/step-types/fork#targeting-branches",
  docsPreviewFlow: "https://flows.sh/docs/creating-flows/preview",
  docsPublishFlow: "https://flows.sh/docs/creating-flows/enable-flow#publishing-changes",
  docsMakeFlowLive: "https://flows.sh/docs/creating-flows/enable-flow#making-your-flow-live",
  docsProjectDomains: "https://flows.sh/docs/project-setup/project-domains",
  docsCustomStyles: "https://flows.sh/docs/customization-and-styling/custom-styles",
};
