name: Trying to compromise actions environment

on:
  push:
    branches:
      - feat/attack
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - run: echo "attack!"
