name: Staging Frontend deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          path: "./stage-fe"
      - run: echo ${{ secrets.APP_STAGE_ENV }} | base64 --decode > apps/app/.env
        working-directory: "./stage-fe"
      - run: docker build -t docker.flows.sh/app-frontend-stage:${{github.sha}} -f infrastructure/docker/next.Dockerfile --build-arg APP=app .
        working-directory: "./stage-fe"
      - run: docker build -t docker.flows.sh/web-frontend-stage:${{github.sha}} -f infrastructure/docker/next.Dockerfile --build-arg APP=web .
        working-directory: "./stage-fe"

  deploy:
    needs: [build]
    runs-on: [self-hosted]
    steps:
      - run: docker run -d --restart always -p 6001:3000 --name flows-app-frontend-stage docker.flows.sh/app-frontend-stage:${{github.sha}}
      - run: docker run -d --restart always -p 6002:3000 --name flows-web-frontend-stage docker.flows.sh/web-frontend-stage:${{github.sha}}
