name: Storybook deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          path: "./storybook"
      - run: docker build -t docker.flows.sh/storybook:${{github.sha}} -f infrastructure/docker/storybook.Dockerfile .
        working-directory: "./storybook"
      - run: docker stop flows-storybook
      - run: docker rm flows-storybook
      - run: docker run -d --restart always -p 6003:80 --name flows-storybook docker.flows.sh/storybook:${{github.sha}}
