name: Staging Supabase deployment

on: workflow_dispatch

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          path: './stage'
      - run: docker compose down
        working-directory: './stage/infrastructure/supabase'
      - run: docker compose up -d 
        working-directory: './stage/infrastructure/supabase'